// import { Button } from "@/components/ui/button";
import React from "react";
import { prisma } from "@/lib/db";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import SignInButton from "@/components/SignInButton";
import { getAuthSession } from "@/lib/nextauth";
import { redirect } from "next/navigation";
import Footer from "@/components/Footer";

export default async function Home() {
  const session = await getAuthSession();
  if (session?.user) {
    redirect("/dashboard");
  }
  return (
    <div className="flex flex-wrap absolute -translate-x-0 -translate-y-0 top-0 left-0">
      <div className="w-full sm:w-8/12 mb-10 mt-14">
        <div className="container mx-auto h-full sm:p-10">
          <nav className="flex px-4 justify-between items-center">
            <div className="text-4xl font-bold">
              Welcome to <span className="text-orange-500">BTEC</span> ESL AI
              Quiz!
            </div>
            <div>
              <img
                src="https://image.flaticon.com/icons/svg/497/497348.svg"
                alt=""
                className="w-8"
              />
            </div>
          </nav>
          <header className="container px-4 lg:flex mt-10 items-center h-full lg:mt-0">
            <div className="w-full">
              <h1 className="text-4xl lg:text-6xl font-bold">
                Where learning <span className="text-orange-500">English</span>{" "}
                is fun!
              </h1>
              <div className="w-20 h-2 bg-orange-500 my-4"></div>
              <p className="text-xl mb-5">
                BTEC ESL (English as Second Language) AI (Artifical
                Intelligence) Quiz is where you can learn English through
                quizziz, all the topics are generated by AI.
              </p>
              <div className="flex items-center space-x-4">
                <span className="text-lg font-semibold">Powered by:</span>
                <img src="BTEC_FPT.png" alt="Logo 1" className="w-15 h-14" />
                <img src="Logo_Fanti.png" alt="Logo 2" className="w-24 h-27" />
              </div>
              <div className="relative inline-flex  group">
                <div className="absolute transitiona-all duration-1000 opacity-70 -inset-px bg-gradient-to-r from-[#ff885d] via-[#00c8fa] to-[#FF675E] rounded-xl blur-lg group-hover:opacity-100 group-hover:-inset-1 group-hover:duration-200 animate-tilt"></div>
                <a
                  title="login"
                  className="relative inline-flex items-center justify-center px-6 py-4 text-lg font-bold text-white transition-all duration-200 bg-gray-900 font-pj rounded-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900"
                  role="button"
                >
                  <SignInButton text="Sign In with Google" />
                </a>
              </div>
            </div>
          </header>
        </div>
      </div>
      <img
        src="English.jpg"
        alt="Wallpaper"
        className="w-full h-48 object-cover sm:h-screen sm:w-4/12"
      />
      <Footer />
    </div>
  );
}
